#!/bin/sh /etc/rc.common
START=99
STOP=04
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/openwrtzapret/recovery-worker
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}
